version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - BEARER_TOKEN=${BEARER_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - EMBED_MODEL=models/embedding-001
      - ANSWER_MODEL=gemini-pro
      - DATA_DIR=/app/data
      - INDEX_DIR=/app/index_store/chroma_db
    volumes:
      - ./data:/app/data
      - ./index_store:/app/index_store
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8000/api
      - NEXT_PUBLIC_BEARER_TOKEN=${BEARER_TOKEN}
    depends_on:
      - backend
    restart: unless-stopped