services:
  - type: web
    name: chatlly-backend
    env: python
    buildCommand: cd backend && apt-get update && apt-get install -y poppler-utils tesseract-ocr && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MICROSOFT_CLIENT_ID
        sync: false
      - key: MICROSOFT_CLIENT_SECRET
        sync: false
      - key: BEARER_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATA_DIR
        value: /opt/render/project/src/data
      - key: INDEX_DIR
        value: /opt/render/project/src/index_store/chroma_db

  - type: web
    name: chatlly-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        fromService:
          type: web
          name: chatlly-backend
          property: url
      - key: NEXT_PUBLIC_BEARER_TOKEN
        sync: false