services:
  - type: web
    name: chatlly-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 8000
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MICROSOFT_CLIENT_ID
        sync: false
      - key: MICROSOFT_CLIENT_SECRET
        sync: false
      - key: BEARER_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATA_DIR
        value: /app/data
      - key: INDEX_DIR
        value: /app/index_store/chroma_db

  - type: web
    name: chatlly-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        fromService:
          type: web
          name: chatlly-backend
          property: url
      - key: NEXT_PUBLIC_BEARER_TOKEN
        sync: false